#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileKahrds.Resource", IsApplication=true)]

namespace MobileKahrds
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttons = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int text_field = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000d
			public const int about = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int createSet = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int deleteQuestion = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int editAnswerField = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int editQuestion = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int editQuestionField = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int games = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int layoutContainer = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int mainMenu = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int manageSet = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int myKahrds = 2131099651;
			
			// aapt resource value: 0x7f060012
			public const int newAnswerField = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int newQuestion = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int newQuestionField = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int newSetField = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayout2 = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int saveQuestion = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int settings = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int spinner = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateSet = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeleteQuestion = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditQuestion = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditSelectedQuestion = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ManageSet = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MyKahrds = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewQuestion = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int main_button_text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int navigation_button_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int text_field = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
